include(FindUnixCommands)

set(CMD "python3 ${DECOMPDRIVER} --meshScript ${MESHDRIVER} -n 90 100 --outDir ${OUTDIR}/mesh -s ${STENCILVAL} --bounds -5.0 5.0 -5.0 5.0 --numDoms 4 3 --overlap 10")
message(NOTICE ${CMD})
execute_process(COMMAND ${BASH} -c ${CMD} RESULT_VARIABLE RES)
if(RES)
  message(FATAL_ERROR "Mesh generation failed")
else()
  message("Mesh generation succeeded!")
endif()

execute_process(COMMAND ${EXENAME} RESULT_VARIABLE CMD_RESULT)
if(RES)
  message(FATAL_ERROR "run failed")
else()
  message("run succeeded!")
endif()

set(CMD "python3 compare.py --golddir ${OUTDIR}")
execute_process(COMMAND ${BASH} -c ${CMD} RESULT_VARIABLE RES)
if(RES)
  message(FATAL_ERROR "comparison failed")
else()
  message("comparison succeeded!")
endif()
